service: serverless-example

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x

custom:
  esbuild:
    bundle: true
    minify: true
    exclude:
      - '@nestjs/platform-express'
      - '@nestjs/microservices'
      - '@nestjs/websockets'
      - 'class-transformer'
      - 'class-validator'
      
functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: GET
          path: /
